// Tutorial Get Random Question
// https://www.shecodes.io/athena/10246-how-to-show-random-questions-in-a-quiz-using-javascript

const questions_ID = [
    `Kalo kamu makan bisa pilih makan malam sama siapa saja, kamu pilih siapa di dunia ini? Dan kenapa dia?`,
    `Kamu mau jadi terkenal gak? Kalo iya dengan cara apa? Kenapa mau jadi terkenal dan kenapa dengan cara itu?`,
    `Sebelum nelpon seseorang, kamu pernah gak latihan dulu apa yang kamu mau ngomong? Kenapa?`,
    `Menurut kamu, hari yang "sempurna" itu seperti apa sih?`,
    `Kapan terakhir kali kamu bernyanyi untuk diri sendiri atau orang lain?`,
    `Kalo kamu bisa hidup sampai 90 tahun, pilih yang mana untuk dipertahankan? Badan atau pikiran seperti orang di umur 30? Dan mengapa?`,
    `Apakah Anda mempunyai firasat rahasia tentang bagaimana Anda akan mati?`,
    `Sebutkan tiga kesamaan yang tampaknya Anda dan pasangan miliki.`,
    `Apa yang paling kamu syukuri didalam hidupmu saat ini? Dan kenapa?`,
    `Jika kamu bisa merubah cara kamu dibesarkan oleh orang tua kamu, apakah itu? Dan kenapa kamu memilih itu?`,
    `Luangkan waktu empat menit dan ceritakan kisah hidup Anda kepada pasangan Anda sedetail mungkin.`,
    `Jika Anda bisa bangun besok dan memperoleh satu kualitas atau kemampuan, apakah itu?`,
    `Jika bola kristal bisa memberi tahu Anda kebenaran tentang diri Anda, kehidupan Anda, masa depan, atau apa pun, apa yang ingin Anda ketahui?`,
    `Apakah ada sesuatu yang sudah kamu mimpikan sejak lama tidak? Jika iya, kenapa kamu belum melakukannya?`,
    `Apa pencapaian terbesar Anda dalam hidup Anda?`,
    `Apa yang paling kamu hargai dalam sebuah persahabatan?`,
    `Apa kenangan Anda yang paling berharga?`,
    `Apa ingatanmu yang paling buruk?`,
    `Jika Anda tahu bahwa dalam satu tahun Anda akan mati mendadak, apakah Anda akan mengubah cara hidup Anda saat ini? Mengapa?`,
    `Apa arti persahabatan bagimu?`,
    `Peran apa yang dimainkan cinta dan kasih sayang dalam hidup Anda?`,
    `Bagikan secara bergantian sesuatu yang Anda anggap sebagai ciri khas positif pasangan Anda. Bagikan total 5 item.`,
    `Seberapa dekat dan hangat keluarga Anda? Apakah Anda merasa masa kecil Anda lebih bahagia dibandingkan masa kecil kebanyakan orang lain?`,
    `Bagaimana perasaanmu tentang hubunganmu dengan ibumu?`,
    `Buatlah masing-masing tiga pernyataan "kita" yang benar. Misalnya saja, “Kita berdua di ruangan ini merasa…”`,
    `Lengkapi kalimat ini: “Saya harap saya memiliki seseorang yang dapat saya ajak berbagi…”`,
    `Jika Anda ingin menjadi teman dekat pasangan Anda, silakan bagikan apa yang penting untuk dia ketahui.`,
    `Beri tahu pasangan Anda apa yang Anda sukai darinya; jujurlah kali ini, katakan hal-hal yang mungkin tidak Anda katakan kepada seseorang yang baru Anda temui.`,
    `Bagikan momen memalukan dalam hidup Anda dengan pasangan Anda.`,
    `Kapan terakhir kali kamu menangis di depan orang lain? Sendiri?`,
    `Beri tahu pasangan Anda sesuatu yang Anda sukai darinya.`,
    `Jika ada, apa yang terlalu serius untuk dijadikan bahan lelucon?`,
    `Jika Anda meninggal malam ini tanpa kesempatan untuk berkomunikasi dengan siapa pun, hal apa yang paling Anda sesali karena tidak memberi tahu seseorang? Kenapa kamu belum memberitahu mereka?`,
    `Rumah Anda, yang berisi semua milik Anda, terbakar. Setelah menyelamatkan orang yang Anda cintai dan hewan peliharaan, Anda punya waktu untuk melakukan langkah terakhir dengan aman untuk menyelamatkan satu item. Apa yang akan terjadi? Mengapa?`,
    `Dari seluruh anggota keluarga Anda, kematian siapa yang paling mengganggu Anda? Mengapa?`,
    `Bagikan masalah pribadi dan mintalah nasihat pasangan Anda tentang bagaimana dia dapat menanganinya. Selain itu, mintalah pasangan Anda untuk merenungkan kembali bagaimana perasaan Anda terhadap masalah yang Anda pilih.`,
    `Sebutkan 3 hal yang terpenting dalam menjalani hubungan!`,
    `Apa peran cinta dan kasih sayang dalam hidup kamu?`,
    `Mimpi apa yang kamu lepaskan dan mengapa?`,
    `Apa pencapaian terbesar dalam hidup Anda?`,
    `Jelaskan saat Anda menyakiti seseorang. Apa yang terjadi dan bagaimana Anda memperbaiki situasi tersebut?`,
    `Apa kenanganmu yang paling berharga?`,
    `Barang apa yang memiliki nilai paling sentimental bagi Anda?`,
    `Ketertarikan Fisik vs Emosi, Mana yang Lebih Dulu?`,
    `Apa ingatanmu yang paling buruk?`,
    `Jika Anda meninggal sekarang, apa yang akan Anda sesali karena tidak memberi tahu seseorang? Dan kenapa kamu belum memberitahu mereka?`,
    `Apa artinya menjadi rentan terhadap pasangan Anda?`,
    `Bagaimana dengan hidup Anda yang Anda harap tidak pernah berubah? Mengapa?`,
    `Apa hal terburuk yang bisa dikatakan seseorang tentangmu?`,
    `Dalam bidang kehidupan apa Anda memercayai diri sendiri?`,
    `Apa ketakutan Anda yang paling konsisten dan terbesar?`,
    `Kapan terakhir kali kamu benar-benar menangis?`,
    `Dalam skala 1-10, seberapa siapkah Anda untuk menjalin hubungan?`,
    `Menurut Anda, seberapa terbuka/rentan saya terhadap Anda?`,
    `Menurut Anda, apa definisi menikah menurut Anda? Mengapa menurut Anda seperti itu?`,
    `Ketika terjadi konflik, apakah Anda lebih memilih bersikap reflektif atau aktif menyelesaikan konflik tersebut?`,
    `Apakah Anda percaya dengan konsep memiliki waktu & ruang pribadi? Mengapa menurut Anda demikian?`,
    `Apakah Anda lebih suka menunjukkan perasaan Anda secara bertahap kepada pasangan? Atau apakah Anda lebih suka menunjukkan semua aspek perasaan Anda terhadap pasangan? Mengapa?`,
    `Menurutmu apakah ada perbedaan antara jatuh cinta dan tetap jatuh cinta? Apa itu? Mengapa menurut Anda demikian?`,
    `Apakah Anda percaya pada kesempatan kedua? Mengapa?`,
    `Apakah aku memiliki tipe yang mirip dengan mantanmu? Apakah saya akrab dengan Anda?`,
    `Apa yang membuat jantungmu berdebar kencang saat aku tidak bersamamu? Apa yang kamu kejar saat aku tidak bersamamu? Kalau kamu jomblo, apa sih yang terus kamu kejar?`,
    `Apa persepsi Anda tentang cinta? Kemelekatan, kenyamanan, keakraban, bekerja menuju visi bersama? Mana yang paling Anda sukai dalam suatu hubungan?`,
    `Jika kamu meninggal malam ini tanpa ada kesempatan untuk berkomunikasi dengan siapapun, hal apa yang akan kamu sesali karena tidak memberi tahu seseorang? Lalu kenapa kamu belum memberi tahu mereka?  `,
    `Dari semua anggota keluarga kamu, kematian siapa yang paling membuat kamu merasa tidak nyaman? mengapa?  `,
    `Komitmen seperti apa yang akan kamu jalani dalam suatu hubungan? `,
    `Pengalaman hal buruk seperti apa yang pernah kamu alami saat menjalin hubungan (pacaran)?`,
    `Jika kamu dihadapkan dengan masalah yang cukup berat, bagaimana cara kamu menyelesaikannya? `,
    `Apa ketakutan terdalam Anda? Mengapa Anda takut akan hal itu?`,
    `Apa momen terberat yang pernah kamu lalui? Bagaimana cara Anda mengatasinya? Apa kesulitannya? Mengapa menurut Anda itu adalah momen tersulit?`,
    `Apa satu hal yang paling Anda pertanyakan dan ingin Anda dapatkan jawabannya?`,
    `Kapan terakhir kali Anda merenung dan berbicara mendalam dengan seseorang? Dengan siapa?`,
    `Apakah kamu lebih suka dikejar? Atau menjadi pengejar? Mengapa?`,
    `Pendekatan seperti apa yang Anda sukai ketika ditanyai sebuah pertanyaan? Pendekatan langsung atau tidak langsung?`,
    `Apa nilai #1 yang Anda cari dalam diri seseorang, dan mengapa?`,
    `Siapa crush pertama kamu? Dan kenapa?`,
    `Apa satu hal yang kamu gak suka dari diri sendiri? Kenapa?`,
    `Kalau kamu stuck di elevator rusak, kamu bakal milih buat stuck sama siapa?`,
    `Menurut kamu,  pertemanan perempuan dan laki-laki apakah bisa tanpa melibatkan perasaan satu sama lain? Kenapa?`,
    `Pernah stalk mantan kamu gak? Buat apa?`,
    `Pernah gak stalk mantanya aku? Kalo iya, kenapa?`,
    `Siapa orang yang belum bisa kamu maafkan sampai saat ini? Kenapa?`,
    `Kamu percaya ga kalau jodoh itu cerminan diri kamu sendiri? Jika iya, apakah kamu bisa mencintai diri sendiri?`,
    `Menurut kamu, FWB itu normal atau nggak sih? Kenapa?`,
    `Mata pelajaran favorit kamu apa? Kenapa kamu pilih mata pelajaran itu?`,
    `Kapan masa tersuram dalam hidup kamu? dan bagaimana caranya kamu bisa menghadapi itu? `,
    `Biasanya orang harus gimana buat nenangin kamu disaat kamu lagi badmood?`,
    `Kalo kamu pilih warna buat ngedeskripsiin `,
    `Motivasi kamu untuk tetap semangat hidup itu apasih?`,
    `Apa arti 'rumah' buat kamu?`,
    `Menurut kamu berapa lama jarak ideal untuk melanjutkan ke hubungan yang lebih serius?`,
    `Kamu lebih menyukai mengobrol secara langsung atau melalui chat/call? kenapa?`,
    `Menurut kamu hal seperti apa yang "sempurna" ?`,
    `Menurut kamu, seberapa penting melakukan 'me time' dalam hubungan?`,
    `Type pasangan kamu seperti apa?`,
    `Seberapa penting zodiak dalam menjalani hubungan?`,
    `Bagaimana cara kamu menangani perasaan bersalah kepada pasangan kamu?`,
    `Sikap pasangan seperti apa yang membuat kamu ilfeel?`,
    `Apakah kamu type pasangan yang posesif dan pencemburu? kenapa?`,
    `Menurut kamu seberapa penting love language dalam hubungan? kenapa? `,
    `Bagaimana cara kalian membagi waktu antara kerja/kuliah dengan pacaran?`,
    `Kapan terakhir kali kamu pacaran?`,
    `What do you expect from your partner ?`,
    `Apa yang akan kamu lakukan ketika salah satu orang tua pasangan kamu tidak menyeyujui hubungan kalian?`,
    `Menurut kamu apakah penting untuk bertukar sosial media dengan pasangan kamu? berikan alasannya`,
    `Jika kamu mendapatkan pasangan yang "strict parent" apa yang akan kamu lakukan? Apakah kamu akan melanjutkan hubungannya?`,
    `Apakah kamu menerapkan batasan-batasan tertentu dalam hubungan? seperti apa?`,
    `Menurut kamu seberapa penting mengatur keuangan dalam hubungan kalian?`,
    `Saat keadaan pasangan kamu sedang 'down' apa yang akan kamu lakukan untuk menghibur/membantunya?`,
    `Saat memulai hubungan, apakah kamu akan langsung menceritakan kepada orang tua mu? kenapa?`,
    `Apa yang kamu harapkan dari pasangan kamu? `,
    `Jika suatu saat pasangan kamu tidak bisa memenuhi ekspetasi kamu, apa yang akan kamu lakukan? `,
    `Saat menghadapi masalah, apakah kamu tipe yang langsung ingin menyelesaikannya atau memberi waktu untuk mendinginkan kepala terlebih dahulu? `,
    `Seberapa percaya kamu dengan pasangan kamu?`,
    `Saat pasangan kamu melakukan kesalahan, apakah kamu akan langsung marah atau menanyakannya terlebih dahulu?`,
    `Bagaimana pendapat kamu mengenai pasangan yang melakukan 'silent treatment' saat ada masalah?`,
    `Selama pacaran dulu ada trauma gak? `,
    `Apa yang kamu pengen aku sering lakuin ke kamu biar kamu happy?`,
    `Sebutin 3 hal yang paling menarik dari aku?`,
    `Tau ga yang paling bikin aku seneng apa?`,
    `Kenapa cewek selingkuh?`,
    `Kenapa cowok selingkuh?`,
    `Di keluarga kamu paling sayang sama siapa? kenapa?`,
    `Kenangan terbaik kamu sama sodara  kandung kamu pas ngapain?`,
    `Kalau lagi hujan, hal ternyaman yang kamu lakukan apa?`,
    `Apa mimpi kecilmu? masi sampe sekarang ga?`,
    `Buat kamu, pernikahan itu apa?`,
    `Siapa orang yang kamu rasa paling nyaman untuk cerita/curhat? Kenapa?`,
    `Kalau kamu dikasi 2 tiket jalan2 ke luar negri, siapa yang kamu ajak?`,
    `Siapa orang yang kamu pengen temuin sekarang, kenapa?`,
    `Buat kamu, mana yang lebih penting, uang atau waktu?`,
    `Kalau kamu bisa baca pikiran, siapa yang kamu mau baca?`,
    `Apa yang kamu pikirin kalo overthingking?`,
    `Aku paling gasuka kalo orang.... aku, karena...`,
    `Aku paling kena kalo cowok ngelakuin ini...`,
    `Aku paling kena bgt kalo cowok ngelakuin ini...`,
    `Kebiasaan apa yang kamu banggain?`,
    `Enak travelling sama pasangan ato temen?`,
    `Ganteng lucu, ato jelek kaya?`,
    `Cantik oon,ato pinter hot`,
    `Best momen waktu kamu lagi berdua sama orang tu ngapain?`,
    `Sebut nama 1 orang cepettt, kenapa kamu sebut dia?`,
    `Klo kamu lahir kembali jadi benda, mau jadi apa?`,
    `Jadi, apa yang bikin kamu terus berjuang sampe sekarang?`,
    `Apa hal yang bikin kamu hampir menyerah?`,
    `Sok cantik itu gimana mnurutmu?`,
    `Sok ganteng itu gimana mnurutmu?`,
    `Kamu yang mana? Menikah dulu? Atau karir dulu? Mengapa?`,
    `Menurut Anda apa tujuan Anda hidup di dunia ini? Sudahkah Anda mengetahuinya? Menurut Anda mengapa itu adalah tujuan Anda?`,
    `Bayangkan di mana diri Anda berada dalam 1, 5, atau 10 tahun ke depan. Mengapa?`,
    `Berapa jam "kehidupan kerja" yang ideal bagi Anda? Apakah menurut Anda bekerja 24/7 itu ideal bagi Anda? Atau apakah Anda lebih suka jam 9 sampai jam 5? Atau Anda lebih suka waktu yang fleksibel?`,
    `Kamu lebih memilih menenangkan diri dulu baru berkencan atau memulai dari nol bersama-sama? Mengapa?`,
    `Memulai hubungan saat sudah siap dalam segala hal atau memulai hubungan dari 0? Kenapa`,
    `Ketika orang tua pasangan kamu tidak merestui hubungan kalian karena kondisi ekonomi kamu, apa yang bakal kamu lakukan?`,
    `Pasangan kamu merupakan picky eater, apa yang akan kamu lakukan? `,
    `Saat first date, siapa yang bayar?`,
    `Kamu lebih mementingkan fisik atau psikis dari pasangan kamu?`,
    `Apakah kamu memilih pasangan yang setara atau berusaha untuk setara?`,
    `Apa definisi selingkuh menurut kamu?`,
    `Saat first date, kamu lebih prefer untuk di jemput atau ketemu di tempat? Kenapa? `,
    `Apakah kamu tertarik untuk pacaran beda agama? Jika ya/tidak berikan alasannya`,
    `Saat pacaran apakah harus ketemu setiap hari? Kenapa?`,
    `Ketika kamu sudah mengalami "lost feelings" dengan pasangan kamu, apa yang akan kamu lakukan? Dan kenapa kamu melakukan itu?`,
    `Saaat ada masalah sama pacar kamu, apakah kamu akan bercerita dengan teman-teman kamu? Kenapa?`,
    `Menurut kamu, apakah bercerita/curhat dengan lawan jenis itu baik? Kenapa?`,
    `Setelah putus dengan pasangan kamu, apakah kamu akan mempertimbangkan untuk balikan atau tidak? Kenapa?`,
    `Menurut kamu move on itu seperti apa?`,
    `Pacaran dengan orang yang lebih tua atau muda? Kenapa`,
    `Gimana pendapat kamu mengenai nikah muda?`,
    `Saat memilih dia untuk menjadi pasangan, apa yang kamu pertimbangkan? Mengapa kamu pertimbangkan hal tersebut?`,
    `Sama kamu sakit, gak sama kamu lebih sakit. Mana yang bakal kamu pilih? Kenapa kamu pilih itu?`,
    `Kamu pengen pacaran berapa lama? Kenapa?`,
    `Apa alasan kamu pacaran?`,
];

const questions_EN = [
    `Given the choice of anyone in the world, whom would you want as a dinner guest?`,
    `Would you like to be famous? If yes, then in what way? Why?`,
    `Before making a telephone call, do you ever rehearse what you are going to say? Why?`,
    `What would constitute a "perfect" day for you?`,
    `When was the last time you sing for yourself or other people?`,
    `If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?`,
    `Do you have a secret hunch about how you will die?`,
    `Name three things you and your partner appear to have in common.`,
    `What is the #1 thing that you are most grateful for in your life currently? Why?`,
    `If you could change anything about the way you were raised, what would it be? And why do you pick that?`,
    `Take four minutes and tell your partner your life story in as much detail as possible.`,
    `If you could wake up tomorrow having gained any one quality or ability, what would it be?`,
    `If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?`,
    `Is there something that you've dreamed of doing for a long time? If yes, why haven't you done it?`,
    `What is your biggest achievements in your life?`,
    `What do you value most in a friendship?`,
    `What is your most treasured memory?`,
    `What is your most terrible memory?`,
    `If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?`,
    `What does friendship mean to you?`,
    `What roles do love and affection play in your life?`,
    `Alternate sharing something you consider a positive characteristic trait of your partner. Share a total of 5 items.`,
    `How close and warm is your family? Do you feel your childhood was happier than most other people's?`,
    `How do you feel about your relationship with your mother?`,
    `Make three true "we" statements each. For instance, "We are both in this room feeling ... "`,
    `Complete this sentence: "I wish I had someone with whom I could share ... "`,
    `If you were going to become a close friend with your partner, please share what would be important for him or her to know.`,
    `Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you've just met.`,
    `Share with your partner an embarrassing moment in your life.`,
    `When did you last cry in front of another person? By yourself?`,
    `Tell your partner something that you like about them already.`,
    `What, if anything, is too serious to be joked about?`,
    `If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven't you told them yet?`,
    `Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?`,
    `Of all the people in your family, whose death would you find most disturbing? Why?`,
    `Share a personal problem and ask your partner's advice on how he or she might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen.`,
    `Name the 3 most important things in a relationship!`,
    `What role does love and affection play in your life?`,
    `What is a dream you let go of and why?`,
    `What is the greatest accomplishment of your life?`,
    `Describe a time you hurt someone. What happened and how did you rectify the situation?`,
    `What's your most treasured memory?`,
    `What item has the most sentimental value to you?`,
    `Physical vs Emotional attraction, which comes first?`,
    `What is your most terrible memory?`,
    `If you were to die right now, what would you regret not having told someone? And why haven't you told them yet?`,
    `What does it mean to be vulnerable with your partner?`,
    `What about your life do you wish you never change? Why?`,
    `What's the worst thing someone could say about you?`,
    `In what area of your life do you trust yourself?`,
    `What is your most consistent and greatest fear?`,
    `When was the last time you really cried?`,
    `On a scale of 1-10 how ready do you feel to be in a relationship?`,
    `How open/vulnerable do you think I am towards you?`,
    `What do you think is your definition of being married? Why do you think that way?`,
    `When there is conflict, would you rather be reflective or be active in resolving the conflict?`,
    `Do you believe in the concept of having personal time & space alone? Why do you think so?`,
    `Would you rather show your feelings gradually to your partner? Or would you rather show all aspects of your feelings towards your partner? Why?`,
    `Do you think that there is a difference between falling in love and staying in love? What is it? Why do you think so?`,
    `Do you believe in second chances? Why?`,
    `Am I of similar type with your ex? Am I familiar to you?`,
    `What is it that keeps your heart beat when I'm not with you? What is it that you chase when I'm not with you? If you're single what is it that you will continuously chase?`,
    `What are your perceptions of love? Attachment, comfort, familiarity, working towards a vision together? Which one do you prefer most to have in a relationship?`,
    `If you died tonight without a chance to communicate with anyone, what would you regret not telling someone? Then why haven't you told them?`,
    `Of all your family members, whose death makes you feel most uncomfortable? Why?`,
    `What kind of commitment will you undertake in a relationship?`,
    `What kind of bad experiences have you had when you were in a relationship (dating)?`,
    `If you are faced with a serious problem, how do you solve it?`,
    `What is your most deepest fear? Why do you fear that?`,
    `What is the toughest moments you've been through? How did you overcame it? What are the difficulties? Why did you thought that that was the toughest moments?`,
    `What is the one thing that you question the most and want to truly get an answer for?`,
    `When was the last time you get to reflect and talk deep with someone? With who?`,
    `Do you prefer to be chased? Or be the chaser? Why?`,
    `What kind of approach do you prefer when being asked a question? A straightforward direct approach or the non straightforward one?`,
    `What is your #1 value that you seek for in a person, and why?`,
    `Who was your first crush? And why?`,
    `What is one thing you don't like about yourself? Why?`,
    `If you were stuck in a broken elevator, who would you choose to be stuck with?`,
    `In your opinion, can women and men be friends without involving each other's feelings? Why?`,
    `Have you ever stalked your ex? What for?`,
    `Have you ever stalked my ex? If yes, why?`,
    `Who is the person you have not been able to forgive until now? Why?`,
    `Do you believe that your soul mate is a reflection of yourself? If yes, can you love yourself?`,
    `In your opinion, FWB is normal or not? Why?`,
    `What's your favorite subject? Why did you choose that subject?`,
    `When was the darkest time in your life? and how can you deal with that?`,
    `What do people usually do to calm you down when you're in a bad mood?`,
    `If you choose a color to describe it`,
    `What is your motivation to stay enthusiastic about life?`,
    `What is the meaning of 'home' to you?`,
    `How long do you think is the ideal distance to move on to a more serious relationship?`,
    `Do you prefer to chat in person or via chat/call? Why?`,
    `What do you think is "perfect"?`,
    `In your opinion, how important is having 'me time' in a relationship?`,
    `What type of partner are you like?`,
    `How important is the zodiac in a relationship?`,
    `How do you handle feelings of guilt towards your partner?`,
    `What kind of partner's attitude makes you feel like you?`,
    `Are you the type of partner who is possessive and jealous? Why?`,
    `How important do you think love language is in a relationship? Why?`,
    `How do you divide your time between work/study and dating?`,
    `When was the last time you dated?`,
    `What do you expect from your partner?`,
    `What will you do when one of your partner's parents does not approve of your relationship?`,
    `Do you think it is important to exchange social media with your partner? give the reason`,
    `If you had a partner who was a "strict parent" what would you do? Will you continue the relationship?`,
    `Do you apply certain boundaries in your relationship? like what?`,
    `How important do you think managing finances is in your relationship?`,
    `When your partner is feeling 'down', what will you do to comfort/help him?`,
    `When you start a relationship, will you immediately tell your parents? Why?`,
    `What do you expect from your partner?`,
    `If one day your partner cannot meet your expectations, what will you do?`,
    `When faced with a problem, are you the type who immediately wants to solve it or give yourself time to cool your head first?`,
    `How much do you trust your partner?`,
    `When your partner makes a mistake, will you immediately get angry or ask him first?`,
    `What do you think about couples who do 'silent treatment' when there is a problem?`,
    `Was there any trauma during your relationship?`,
    `What do you want me to do to you often to make you happy?`,
    `What are the 3 most interesting things about me?`,
    `Do you know what makes me most happy?`,
    `Why do girls cheat?`,
    `Why do guys cheat?`,
    `Who do you love most in your family? Why?`,
    `What are your best memories with your siblings?`,
    `If it's raining, what's the most comfortable thing for you to do?`,
    `What's your little dream? is it still up to now?`,
    `For you, what is marriage?`,
    `Who is the person you feel most comfortable telling/confiding with? Why?`,
    `If you were given 2 tickets to travel abroad, who would you take?`,
    `Who is the person you want to meet now, why?`,
    `For you, which is more important, money or time?`,
    `If you could read minds, who would you want to read?`,
    `What do you think if you overthink?`,
    `I really hate it when people... me, because...`,
    `I really hate it when guys do this...`,
    `I really hate it when guys do this...`,
    `What habits are you proud of?`,
    `Do you enjoy traveling with your partner or friends?`,
    `Handsome, cute, or ugly?`,
    `You're beautiful, or smart, hot`,
    `What's the best moment when you're alone with that person?`,
    `Quickly mention one person's name, why did you mention him?`,
    `If you were born again as an object, what would you be?`,
    `So, what keeps you fighting until now?`,
    `What made you almost give up?`,
    `What do you think is beautiful?`,
    `What do you think is handsome?`,
    `Which one are you? Married first? Or career first? Why?`,
    `What do you think is your purpose of living in this world? Have you find that out? Why do you think that is your purpose?`,
    `Where do you imagine yourself to be in the next 1, 5 or 10 years. Why?`,
    `What is your ideal "work-life" hour for you? Do you think working 24/7 is ideal for you? Or do you prefer 9 to 5? Or do you prefer flexible time?`,
    `Do you prefer to settle yourself first then date or start from zero together? Why?`,
    `Start a relationship when you are ready for everything or start a relationship from 0? Why? `,
    `When your partner's parents don't approve of your relationship because of your economic conditions, what will you do?`,
    `Your partner is a picky eater, what will you do?`,
    `On the first date, who pays?`,
    `Do you care more about the physical or psychological aspects of your partner?`,
    `Do you choose equal partners or try to be equal?`,
    `What is the definition of cheating according to you?`,
    `On your first date, do you prefer to be picked up or met locally? Why?`,
    `Are you interested in dating from a different religion? If yes/no, give reasons`,
    `When you're dating, do you have to see each other every day? Why?`,
    `When you have experienced "lost feelings" with your partner, what will you do? And why do you do that?`,
    `When you have a problem with your boyfriend, will you tell your friends? Why?`,
    `In your opinion, is it good to talk/confide in people of the opposite sex? Why?`,
    `After breaking up with your partner, will you consider getting back together or not? Why?`,
    `What do you think moving on looks like?`,
    `Dating someone older or younger? Why`,
    `What do you think about young marriage?`,
    `When choosing him to be your partner, what did you consider? Why are you considering this?`,
    `The same as you are sick, not the same as you are sicker. Which one will you choose? Why did you choose that?`,
    `How long do you want to date? Why?`,
    `Why are you dating? `,
];

// console.log(questions.length);

const getRandomIndexBasedOnLength = (array) => {
    return Math.floor(Math.random() * array.length);
};

const removeRandomQuestion = (index, array) => {
    if (index > -1) {
        array.splice(index, 1);
    }
};

const getRandomQuestion = (index, array) => {
    return array[index];
};

export const stack_ID = [];
export const stack_EN = [];

// Limit to 10 questions
// for (let i = 0; i < 10; i++) {
//     var randomIndex = getRandomIndexBasedOnLength(questions);
//     stack.push(getRandomQuestion(randomIndex, questions));
//     removeRandomQuestion(randomIndex, questions);
// }

var questionLengthFixed_ID = questions_ID.length;
var questionLengthFixed_EN = questions_EN.length;

// Get all questions at random order - Indonesian
for (let i = 0; i < questionLengthFixed_ID; i++) {
    var randomIndex = getRandomIndexBasedOnLength(questions_ID);
    stack_ID.push(getRandomQuestion(randomIndex, questions_ID));
    removeRandomQuestion(randomIndex, questions_ID);
}

for (let i = 0; i < questionLengthFixed_EN; i++) {
    var randomIndex = getRandomIndexBasedOnLength(questions_EN);
    stack_EN.push(getRandomQuestion(randomIndex, questions_EN));
    removeRandomQuestion(randomIndex, questions_EN);
}

// console.log(questions_EN.length);
// console.log(questions_ID.length);

// console.log(stack_EN.length);
// console.log(stack_ID.length);
