export const questions = [
    "Apa arti rumah untukmu?",
    "Apa arti cinta untukmu?",
    "Apa arti kebahagiaan untukmu?",
    "Menurut kamu, apa batasan antara egois dan mencintai diri sendiri?",
    "Apa kelebihan dan kekurangan diri kamu?",
    "Menurut kamu apakah seorang teman yang sejati harus ada di sampingmu ketika kamu sedang mengalami patah hati?",
    "Deskripsikan akhir pekan yang ideal menurut kamu.",
    "Kamu lebih suka hubungan jarak jauh (LDR) atau tidak? Kenapa?",
    "Diberi pilihan siapa pun di dunia, siapa yang Anda inginkan sebagai tamu makan malam?",
    "Apakah Anda ingin terkenal? Dengan cara apa?",
    "Sebelum melakukan panggilan telepon, apakah Anda pernah melatih apa yang akan Anda katakan? Mengapa?",
    'Apa yang akan menjadi hari yang "sempurna" untukmu?',
    "Kapan terakhir kali Anda bernyanyi untuk diri sendiri? Untuk orang lain?",
    "Jika Anda dapat hidup hingga usia dan mempertahankan pikiran atau tubuh berusia 30 tahun selama bertahun-tahun terakhir dalam hidup Anda, mana yang Anda inginkan?",
    "Apakah Anda memiliki firasat rahasia tentang bagaimana Anda akan mati?",
    "Sebutkan tiga hal yang Anda dan pasangan Anda nampak sama.",
    "Untuk apa dalam hidup Anda, Anda merasa paling berterima kasih?",
    "Jika Anda bisa mengubah apa pun tentang cara Anda dibesarkan, apakah itu?",
    "Luangkan empat menit dan ceritakan kisah hidup Anda sebanyak mungkin.",
    "Jika Anda bisa bangun besok setelah mendapatkan satu kualitas atau kemampuan, apakah itu?",
    "Jika bola kristal bisa memberi tahu Anda kebenaran tentang diri Anda, hidup Anda, masa depan atau apa pun, apa yang ingin Anda ketahui?",
    "Apakah ada sesuatu yang telah Anda impikan untuk waktu yang lama? Kenapa kamu belum melakukannya? ",
    "Apa pencapaian terbesar dalam hidup Anda?",
    "Apa yang paling Anda hargai dalam persahabatan?",
    "Apa ingatanmu yang paling berharga?",
    "Apa ingatanmu yang paling mengerikan?",
    "Jika Anda tahu bahwa dalam satu tahun Anda akan mati mendadak, apakah Anda akan mengubah apa pun tentang cara Anda sekarang hidup? Mengapa?",
    "Apa arti persahabatan bagi Anda?",
    "Peran apa yang dimainkan cinta dan kasih sayang dalam hidup Anda?",
    "Alternatif berbagi sesuatu yang Anda anggap sebagai karakteristik positif dari pasangan Anda. Bagikan total lima item. ",
    "Seberapa dekat dan hangat keluargamu? Apakah Anda merasa masa kecil Anda lebih bahagia daripada kebanyakan orang lain? ",
    "Bagaimana perasaan Anda tentang hubungan Anda dengan ibumu?",
    'Buat tiga pernyataan "kami" yang benar. Misalnya, "Kami berdua di ruangan ini merasa ..." ',
    'Selesaikan kalimat ini: "Saya berharap saya memiliki seseorang yang bisa saya bagikan ..."',
    "Jika Anda akan menjadi teman dekat dengan pasangan Anda, silakan bagikan apa yang akan penting baginya untuk diketahui.",
    "Beri tahu pasangan Anda apa yang Anda sukai dari mereka; Jujur saja kali ini, mengatakan hal -hal yang mungkin tidak Anda katakan kepada seseorang yang baru saja Anda temui. ",
    "Bagikan dengan pasanganmu momen yang memalukan dalam hidupmu.",
    "Kapan terakhir kali Anda menangis di depan orang lain? Sendiri?",
    "Beri tahu pasangan Anda sesuatu yang Anda sukai dari mereka.",
    "Apa, jika ada, yang terlalu serius untuk bercanda?",
    "Jika Anda mati malam ini tanpa kesempatan untuk berkomunikasi dengan siapa pun, apa yang paling Anda sesali tidak memberi tahu seseorang? Mengapa Anda belum memberi tahu mereka? ",
    "Rumah Anda, berisi semua yang Anda miliki, terbakar. Setelah menyelamatkan orang yang Anda cintai dan hewan peliharaan, Anda memiliki waktu untuk dengan aman membuat tanda hubung terakhir untuk menyimpan satu item. Apa yang akan terjadi? Mengapa?",
    "Dari semua orang di keluarga Anda, kematian siapa yang menurut Anda paling mengganggu? Mengapa?",
    "Bagikan masalah pribadi dan tanyakan saran pasangan Anda tentang bagaimana ia dapat mengatasinya. Juga, minta pasangan Anda untuk merenungkan kembali kepada Anda bagaimana perasaan Anda tentang masalah yang telah Anda pilih. ",
];
